### ISSUE TITLE
Keycloak 19.0.2 -  "User federation provider could not be created: unknown_error" when adding provider 

### ISSUE THREAD

**Issue by jongreene76** [opensingular/singular-keycloak-database-federation#25] opened 2022-10-01 19:46 UTC
When attempting to add a provider using this SPI in version 19.0.2 Keycloak shows "User federation provider could not be created: unknown_error"

**Comment by jongreene76** [comment] 2022-10-01 23:39
If you switch the Master realm Theme from "Keycloak.v2" to the original "Keycloak" theme the error no longer occurs.

**Comment by viniciusuriel** [comment] 2022-10-03 18:32
This issue is a duplicate of #19 , the solution is exactly the one you figured out.

**Closed as completed by viniciusuriel** 2022-10-03 18:32 UTC
